---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    ignore:
      # Newer versions have a bug that causes a false failure, see #153
      - dependency-name: gaurav-nelson/github-action-markdown-link-check
