---
# Breaks reusing MD snippets extracted to files
first-line-heading: false

# Set maximum line Length to 140c to match Go linting
line-length:
  line_length: 140

# Allow HTML span elements to set font sizes
no-inline-html:
  allowed_elements:
    - span

# Enforce our capitalisation rules (where they're unambiguous)
# Terms listed here should also be listed in the style guide
# https://submariner.io/development/website/style-guide/#submarinerio-word-list
spelling:
  names:
    - Admiral
    - ClusterSet
    - Coastguard
    - Globalnet
    - IPsec
    - iptables
    - kind
    - Kubernetes
    - Lighthouse
    - OpenStack
    - Shipyard
    - subctl
    - Submariner
    - VXLAN
  code_blocks: false
