@startuml
!theme plain
actor operator

box Cluster 1
participant CA
participant CA_CSR_Syncer
participant Broker
participant C1_API
end box

box Cluster 2
participant GW_CSR_Syncer
participant Gateway
participant C2_API
end box

CA_CSR_Syncer->C1_API: 0. Watch CSRs


operator -> Gateway: 1. Deploy Cluster 2 Gateway
Gateway->GW_CSR_Syncer: 2. New CSR Syncer
GW_CSR_Syncer->C2_API: 3.Watch CSRs
Gateway->Gateway: 4.Create CSR (via openssl)
Gateway->C2_API: 5. Create CSR CR
C2_API->GW_CSR_Syncer: 6. Notify CSR CR
GW_CSR_Syncer->Broker: 7. Export CSR CR
Broker->GW_CSR_Syncer: 8. Notify new CSR CR
Broker->CA_CSR_Syncer: 8. Notify new CSR CR
CA_CSR_Syncer->CA_CSR_Syncer: 9. Create actual CSR for CA
CA_CSR_Syncer->CA: 10. Send CSR
CA->C1_API: 11. Sign CSR
C1_API->CA_CSR_Syncer: 15. Notify CSR CR
CA_CSR_Syncer->Broker: 16. Update and Export CSR CR
Broker->CA_CSR_Syncer: 17. Notify new CSR CR
Broker->GW_CSR_Syncer: 17. Notify new CSR CR
GW_CSR_Syncer->Gateway: 18. Pass Signed Cert and encrypted Private Key
Gateway->Gateway: 18. Decrypt Private Key, use cert for Cable Driver
Gateway->C2_API: 19. Delete CSR CR
C2_API->GW_CSR_Syncer: 20. Notify Delete CSR CR
GW_CSR_Syncer->Broker: 21. Delete CSR CR
@enduml